### ISSUE TITLE
[FEATURE] User can log in

### ISSUE THREAD

**Issue by otienodominic** [BuildForSDG/JaliAjali#4]
**User should be able to signin**
A user interested in getting more customized information, create connections with other users, should be able to sign in.

**How to sign in**
A user shall provide one time information during registration process. this will include *but not limited to*:
- First name
- Last name
- Gender
- email
- Username
- Password

**Security**
User password should be encrypted before storage into the database. Due diligenge should be ensured that email is correct since this will be the primary communication with registered clients

**Comment by lewis-munyi** [comment]
Users shouldn't be able to sign in. It is a crowdsourcing app, therefore, it doesn't need all that.
